Company/urls.py
from django.urls import path

from Company.views import CompanyViews, CompanyDetail, CompanyAdd, CompanyDelete

app_name = 'company'

urlpatterns = [
    path('', CompanyViews.as_view(), name='company'),
    path('detail/<int:pk>/', CompanyDetail.as_view(), name='detail_company'),
    path('add/', CompanyAdd.as_view(), name='add_company'),
    path('delete/<int:pk>/', CompanyDelete.as_view(), name='delete_company'),
]

Director/urls.py
from django.urls import path

from Director.views import DirectorViews, DirectorDetail, DirectorAdd

app_name = 'directors'

urlpatterns = [
    path('', DirectorViews.as_view(), name='directors'),
    path('detail/<int:pk>/', DirectorDetail.as_view(), name='detail_directors'),
    path('add/', DirectorAdd.as_view(), name='add_directors'),

]

bank/urls.py
from django.urls import path

from bank.views import BankViews, BankAdd, BankAll, BankMailAccount, BankMailAccount_update

app_name = 'bank'

urlpatterns = [
    path('', BankViews.as_view(), name='bank'),
    path('add_bank/', BankAdd.as_view(), name='bank_add'),
    path('all_bank/', BankAll.as_view(), name='bank_all'),
    path('mail_account/<int:pk>', BankMailAccount.as_view(), name='mail_account'),
    path('update_mail/<int:pk>', BankMailAccount_update.as_view(), name='mail_account_update'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directors/', include('Director.urls')),
    path('company/', include('Company.urls')),
    path('', include('bank.urls')),
    path('webhooks/', include('webhooks.urls')),

]

Director/models.py
from datetime import date

from django.db import models


class Director(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО')
    inn = models.CharField(max_length=30, verbose_name='ИНН')
    date_of_birth = models.DateField(default=date.today, verbose_name='Дата рождения')
    place_of_birth = models.CharField(max_length=255, verbose_name='Место рождения')
    id_passport = models.CharField(max_length=10, verbose_name='Номер паспорта')
    date_of_issue = models.CharField(max_length=10, verbose_name='Дата выдачи')
    issued_by = models.CharField(max_length=255, verbose_name='Кем выдан')
    department_сode = models.CharField(max_length=7, verbose_name='Код подразделения')
    street = models.CharField(max_length=255, verbose_name='Улица')
    house = models.CharField(max_length=255, verbose_name='Дом')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Директор'
        verbose_name_plural = 'Директора'

    def save(self, *args, **kwargs):

        self.name = self.name.title()
        super().save(*args, **kwargs)

Director/forms.py
from django import forms
from django.forms import IntegerField

from Director.models import Director


class DateInput(forms.DateInput):
    input_type = 'date'


class DirectorsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите ФИО'}), label='Фамилия Имя Отчество')
    inn = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите ИНН'}), label='ИНН')
    date_of_birth = forms.DateField(widget=DateInput(), label='Дата рождения')
    id_passport = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Введите Номер паспорта'}),
                                     label='Номер паспорта')
    date_of_issue = forms.DateField(widget=DateInput(), label='Дата выдачи')
    issued_by = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите Кем выдан'}), label='Кем выдан')
    department_сode = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Введите Код подразделения'}),
                                         label='Код подразделения')
    street = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите Улицу'}), label='Улица')
    house = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Введите Дом'}), label='Дом')

    class Meta:
        model = Director
        fields = ['name', 'inn', 'date_of_birth', 'id_passport', 'date_of_issue', 'issued_by', 'department_сode',
                  'street', 'house']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"

Director/views.py
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView

from Company.models import Company
from Director.forms import DirectorsForm
from Director.models import Director

from Director.utils import check_age


class DirectorViews(ListView):
    model = Director
    context_object_name = 'latest_articles'
    template_name = "Director/directors.html"


class DirectorAdd(CreateView):
    form_class = DirectorsForm
    template_name = "Director/director_form.html"

    def get_success_url(self):
        return reverse('directors:directors')


class DirectorDetail(DetailView):
    model = Director
    template_name = "Director/director_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['age'] = check_age(self.object.date_of_birth)
        context['firms'] = Company.objects.filter(directors_id=self.object.pk)
        return context

Director/templates/Director/director_detail.html
{% extends "home.html" %}
{% block title %} Info Directors {% endblock title %}
{% block header %} Информация о директоре {% endblock header %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h5>Полных лет: {{age}}</h5>
            <h5>ФИО: {{object.name}}</h5>
            <h5>ИНН: {{object.inn}}</h5>
            <h5>Дата рождения: {{object.date_of_birth}}</h5>
            <h5>Место рождения: {{object.place_of_birth}}</h5>
            <h5>Номер паспорта: {{object.id_passport}}</h5>
            <h5>Дата выдачи: {{object.date_of_issue}}</h5>
            <h5>Кем выдан: {{object.issued_by}}</h5>
            <h5>Код подразделения: {{object.department_сode}}</h5>
            <h5>Улица: {{object.street}}</h5>
            <h5>Дом: {{object.house}}</h5>
            <h5>Кем выдан: {{object.issued_by}}</h5>
            <h5>Фирмы:
                {% for firm in firms %}

                <a href="{% url 'company:detail_company' firm.pk %}"></br>{{firm}}</a>
                {% endfor %}
            </h5>
        </div>
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">

    </div>

</div>


<div class="row">
    <form action="{% url 'company:delete_company' object.pk %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-warning"> Редактировать</button>
    </form>
    <form action="{% url 'company:delete_company' object.pk %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-danger"> Удалить</button>
    </form>
</div>

{% endblock content %}

Director/templates/Director/director_form.html
{% extends "home.html" %}
{% block title %} Форма добавления директора {% endblock title %}
{% block header %} Добавление директора {% endblock header %}


{% block content %}
    <form class="form-group" method="post">{% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for={{ form.name.id_for_label }}>{{ form.name.label }}</label>
                {{ form.name }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.date_of_birth.id_for_label }}>{{ form.date_of_birth.label }}</label>
                {{ form.date_of_birth }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.inn.id_for_label }}>{{ form.inn.label }}</label>
                {{ form.inn }}
            </div>

        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for={{ form.issued_by.id_for_label }}>{{ form.issued_by.label }}</label>
                {{ form.issued_by }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.id_passport.id_for_label }}>{{ form.id_passport.label }}</label>
                {{ form.id_passport }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.date_of_issue.id_for_label }}>{{ form.date_of_issue.label }}</label>
                {{ form.date_of_issue }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.department_сode.id_for_label }}>{{ form.department_сode.label }}</label>
                {{ form.department_сode }}
            </div>


        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for={{ form.street.id_for_label }}>{{ form.street.label }}</label>
                {{ form.street }}
            </div>
            <div class="form-group col-md-2">
                <label for={{ form.house.id_for_label }}>{{ form.house.label }}</label>
                {{ form.house }}
            </div>

        </div>
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
    <div class="row">
        <div class="col-md-1">
            <a class="btn btn-danger" href="{% url 'company:add_company' %}" role="button">Назад</a>
        </div>
    </div>

{% endblock content %}

Director/templates/Director/directors.html
{% extends "home.html" %}
{% block title %} Directors {% endblock title %}
{% block header %} Список директоров {% endblock header %}


{% block content %}
<div class="row">
    <div class="col-md-12 mx-auto my-2">
    <table class="table table-striped">
        <tr>
            <th>ФИО</th>
            <th>ИНН</th>
            <th>Дата рождения</th>
            <th>Место рождения</th>
            <th>Номер паспорта</th>
            <th>Дата выдачи</th>
            <th>Кем выдан</th>
            <th>Код Подразделения</th>
            <th>Улица</th>
            <th>Дом</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><a href="{% url 'directors:detail_directors' object.pk%}">{{object.name}}</a></td>
            <td>{{object.inn}}</td>
            <td>{{object.date_of_birth}}</td>
            <td>{{object.place_of_birth}}</td>
            <td>{{object.id_passport}}</td>
            <td>{{object.date_of_issue}}</td>
            <td>{{object.issued_by}}</td>
            <td>{{object.department_сode}}</td>
            <td>{{object.street}}</td>
            <td>{{object.house}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
</div>
<div class="row">
    <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'directors:add_directors' %}" role="button">Добавить</a>
    </div>
</div>
{% endblock content %}