Company/urls.py
from django.urls import path

from Company.views import CompanyViews, CompanyDetail, CompanyAdd, CompanyDelete

app_name = 'company'

urlpatterns = [
    path('', CompanyViews.as_view(), name='company'),
    path('detail/<int:pk>/', CompanyDetail.as_view(), name='detail_company'),
    path('add/', CompanyAdd.as_view(), name='add_company'),
    path('delete/<int:pk>/', CompanyDelete.as_view(), name='delete_company'),
]

bank/urls.py
from django.urls import path

from bank.views import BankViews, BankAdd, BankAll, BankMailAccount, BankMailAccount_update

app_name = 'bank'

urlpatterns = [
    path('', BankViews.as_view(), name='bank'),
    path('add_bank/', BankAdd.as_view(), name='bank_add'),
    path('all_bank/', BankAll.as_view(), name='bank_all'),
    path('mail_account/<int:pk>', BankMailAccount.as_view(), name='mail_account'),
    path('update_mail/<int:pk>', BankMailAccount_update.as_view(), name='mail_account_update'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directors/', include('Director.urls')),
    path('company/', include('Company.urls')),
    path('', include('bank.urls')),
    path('webhooks/', include('webhooks.urls')),

]

bank/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone


class Bank(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название Банка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Банк'
        verbose_name_plural = 'Банки'


class BankAccount(models.Model):
    company = models.ForeignKey('Company.Company', null=True, on_delete=models.CASCADE, verbose_name='Фирма',
                                related_name='company')
    bank = models.ForeignKey('Bank', null=True, on_delete=models.CASCADE, verbose_name='Банк', related_name='bank')
    login_bank = models.CharField(max_length=255, verbose_name='Логин', null=False)
    password_bank = models.CharField(max_length=255, verbose_name='Пароль', null=False)

    date_created = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(auto_now_add=True)
    balance = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, default=0)
    in_block = models.BooleanField(default=False, verbose_name="В блоке")

    def update(self, *args, **kwargs):
        super().update(*args, **kwargs)
        return self

    def __str__(self):
        return f'{self.company.name + "|" + self.bank.name}'

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'
        ordering = ["bank_id"]


class Mailbank(models.Model):
    account = models.ForeignKey('BankAccount', on_delete=models.CASCADE, verbose_name='Аккаунт',
                                related_name='bankaccounts')
    date_mail = models.DateTimeField(null=True)
    title_mail = models.CharField(max_length=255, null=True, verbose_name='Заголовок письма')
    content_mail = models.TextField(null=True)
    sender_mail = models.CharField(max_length=255, null=True, verbose_name='Отправитель')
    publication_mail = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.account}'

    def get_absolute_url(self):
        return '/'

    # def read_mail(self, id):
    #     mail = Mailbank.objects.get(id=id)
    #     mail.publication_mail = False
    #     mail.save()
    #     return

bank/forms.py
from django import forms

from Company.models import Company
from bank.models import Mailbank, BankAccount, Bank


class BankAccountForm(forms.ModelForm):
    company = forms.ModelChoiceField(queryset=Company.objects.all(), label='Компания')
    bank = forms.ModelChoiceField(queryset=Bank.objects.all(), label='Банк')
    login_bank = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите логин акаунта'}), label='Логин')
    password_bank = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите пароль аккаунта'}),
                                    label='Пароль')

    class Meta:
        model = BankAccount
        fields = ['company', 'bank', 'login_bank', 'password_bank']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"


class MailForms(forms.ModelForm):
    class Meta:
        model = Mailbank

        fields = [
            'publication_mail'
        ]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object['publication_mail'] = False
        self.object.save()
        return super().form_valid(form)

bank/views.py
from datetime import datetime, timedelta
from django.db.models import Q
from django.db.models import Sum, Min, Count
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from Company.models import Company
from bank.forms import MailForms, BankAccountForm
from bank.models import BankAccount, Bank, Mailbank


class BankViews(ListView):
    model = BankAccount
    template_name = 'bank/bank.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        date = datetime.today() - timedelta(days=1)

        context = {
            'companies': Company.objects.all().order_by('id'),
            'banks': Bank.objects.all().order_by('id'),
            'bank_accounts': BankAccount.objects.all().order_by('company_id'),
            'balance': BankAccount.objects.aggregate(balance=Sum('balance', decimal_places=2),
                                                     date_updated=Min('date_updated')),
            'all_balance': BankAccount.objects.values('bank__name').order_by('bank_id').annotate(total=Sum('balance'),
                                                                                                 date_updated=Min(
                                                                                                     'date_updated')),
            'bal_firm': BankAccount.objects.values('company__name').order_by('company_id').annotate(
                total=Sum('balance')),
            'date_error': BankAccount.objects.filter(date_updated__startswith=date.date()).select_related('company',
                                                                                                          'bank'),
            'mail_accounts': Mailbank.objects.values('account_id').order_by('account_id').annotate(
                count=Count('id', filter=Q(publication_mail=True)),
            )
        }
        print(context['bank_accounts'])
        return context


class BankAll(ListView):
    model = BankAccount
    context_object_name = 'latest_articles'
    template_name = "bank/bank_all.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['all_list'] = BankAccount.objects.select_related('company', 'bank').order_by('-date_updated').all()
        return context


# class BankAdd(CreateView):
#     model = BankAccount
#     template_name = "bank/bank_form.html"
#     fields = '__all__'
#
#     def get_success_url(self):
#         return reverse('bank:bank')

class BankAdd(CreateView):
    form_class = BankAccountForm
    template_name = "bank/bank_form.html"

    def get_success_url(self):
        return reverse('bank:bank')


class BankMailAccount_update(UpdateView):
    model = Mailbank
    form_class = MailForms


class BankMailAccount(ListView):
    model = Mailbank
    template_name = 'bank/mail_account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = context['object_list'][0]
        return context

    def get_queryset(self):
        return Mailbank.objects.filter(account_id=self.kwargs['pk'])

bank/templates/bank/bank.html
{% extends "home.html" %}
{% block title %} Банки {% endblock title %}
{% block header %} Список Банков {% endblock header %}
{% load humanize %}


{% block content %}
<div class="row">
    <div class="col-md-3">
        <form action="{% url 'bank:bank' %}" method="GET">
            {% csrf_token %}
            <input type="submit" class="btn btn-success"
                   value="Общий баланс :   {{balance.balance|intcomma}} рублей">
        </form>
    </div>
    <div class="col-md-6">

    </div>
    <div class="col-md-2">
        <h6 data-tooltip title="{% for error in date_error %}{{error}}{%endfor%}"><b>{{balance.date_updated|naturaltime}}</b></h6>
    </div>
</div>
<div class="row">
    <div class="col-md-12 my-2">
        <table class="col-md-12">
            <tr>
                {% for i in all_balance %}
                <th>{{i.bank__name}}: <span style="color: forestgreen">{{i.total|intcomma}}</span></th>
                {%endfor%}
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12 my-2">
        <table class="table table-bordered">
            <tr>
                <th></th>
                {% for company in companies %}
                <th style="text-align: center">{{ company.name|cut:'ООО'|cut:'"' }}</th>
                {% endfor %}
            </tr>
            {% for bank in banks %}
            <tr>
                <th>{{bank.name}}</th>
                {% for company in companies %}
                <td style="min-width: 100px; text-align:center">
                    {% for account in bank_accounts %}
                        {% if account.company_id == company.id and bank.id == account.bank_id%}
                                <span {% if account.in_block %} style="color:red" {% endif %}>{{account.balance}}</span>
                        {% for mail in mail_accounts %}
                            {% if account.id == mail.account_id and mail.count > 0 %}
                                <a href="{% url 'bank:mail_account' account.id%}" data-tooltip2 title="{{mail.count}}"><img src="https://image.flaticon.com/icons/png/512/646/646094.png" width="15"
  height="15"></a>
                            {%endif%}
                        {% endfor %}
<!--                        {{account.date_update}}-->
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
            <tr>
                <th>ИТОГО</th>
                {% for company in companies %}
                <td style="text-align: center">
                    {% for com in bal_firm%}
                        {% if company.name == com.company__name %}
                            <b>{{com.total|intcomma}}</b>
                        {%endif%}
                    {%endfor%}
                </td>
                {% endfor %}
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'bank:bank_add' %}" role="button">Добавить</a>
    </div>
</div>
{% endblock %}

bank/templates/bank/bank_all.html
{% extends "home.html" %}
{% block title %} Компании {% endblock title %}
{% block header %} Список фирм {% endblock header %}


{% block content %}
<div class="row">

</div>
<div class="row">
    <div class="col-md-10 mx-auto my-2">
        <table class="table table-striped">
            <tr>
                <th>Название банка</th>
                <th>Название фирмы</th>
                <th>Баланс</th>
                <th>Дата создания</th>
                <th>Дата обновления</th>
                <th>Логин</th>
                <th>Пароль</th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>{{object.bank.name}}</td>
                <td>{{object.company.name}}</td>
                <td><b>{{object.balance}}</b></td>
                <td>{{object.date_created}}</td>

                    <td>{{object.date_updated | timesince}}</td>

                <td>{{object.login_bank |truncatechars:30}}</td>
                <td>{{object.password_bank}}</td>

            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

bank/templates/bank/bank_form.html
{% extends "home.html" %}
{% block title %} Добавить аккаунт банка {% endblock title %}
{% block header %} Добавление аккаунта {% endblock header %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <form class="form-group" method="post">{% csrf_token %}
            {{ form.as_p }}
                <input type="submit" class="btn btn-success" value="Сохранить">
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <a class="btn btn-primary" href="{% url 'company:add_company' %}" role="button">Добавить фирму</a>
        <a class="btn btn-danger" href="{% url 'bank:bank' %}" role="button">Назад</a>
    </div>
</div>
{% endblock %}

bank/templates/bank/mail_account.html
{% extends "home.html" %}
{% block title %} Почта {% endblock title %}
{% block header %} Почта аккаунта {{object}} {% endblock header %}


{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <table class="table table-striped">
                <tr>
                    <th>От Кого</th>
                    <th>Дата</th>
                    <th>Тема письма</th>
                    <th>Содержание</th>
                    <th>Прочитать</th>
                </tr>
                {% for object in object_list %}
                {% if object.publication_mail %}
                    <tr>
                        <td>{{object.sender_mail}}</td>
                        <td>{{object.date_mail}}</td>
                        <td>{{object.title_mail |truncatechars:50}}</td>
                        <td>{{object.content_mail |truncatechars:100}}</td>
                        <td>
                            <form action="{% url 'bank:mail_account_update' object.pk %}" method="post">{% csrf_token %}
                                <button type="submit" class="btn btn-danger"> Пометить как прочитано</button>
                            </form>
                        </td>
                    </tr>
                {%endif %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}