Company/urls.py
from django.urls import path

from Company.views import CompanyViews, CompanyDetail, CompanyAdd, CompanyDelete

app_name = 'company'

urlpatterns = [
    path('', CompanyViews.as_view(), name='company'),
    path('detail/<int:pk>/', CompanyDetail.as_view(), name='detail_company'),
    path('add/', CompanyAdd.as_view(), name='add_company'),
    path('delete/<int:pk>/', CompanyDelete.as_view(), name='delete_company'),
]

Director/urls.py
from django.urls import path

from Director.views import DirectorViews, DirectorDetail, DirectorAdd

app_name = 'directors'

urlpatterns = [
    path('', DirectorViews.as_view(), name='directors'),
    path('detail/<int:pk>/', DirectorDetail.as_view(), name='detail_directors'),
    path('add/', DirectorAdd.as_view(), name='add_directors'),

]

bank/urls.py
from django.urls import path

from bank.views import BankViews, BankAdd, BankAll, BankMailAccount, BankMailAccount_update

app_name = 'bank'

urlpatterns = [
    path('', BankViews.as_view(), name='bank'),
    path('add_bank/', BankAdd.as_view(), name='bank_add'),
    path('all_bank/', BankAll.as_view(), name='bank_all'),
    path('mail_account/<int:pk>', BankMailAccount.as_view(), name='mail_account'),
    path('update_mail/<int:pk>', BankMailAccount_update.as_view(), name='mail_account_update'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directors/', include('Director.urls')),
    path('company/', include('Company.urls')),
    path('', include('bank.urls')),
    path('webhooks/', include('webhooks.urls')),

]

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{% block title %} First
    {% endblock title %}
    </title>
    <link href="{% static 'css/jquery.fias.min.css' %}" rel="stylesheet">
<script src="{% static 'lib/jquery-1.11.1.min.js' %} " type="text/javascript"></script>
    <script src="{% static 'js/jquery.fias.min.js' %} " type="text/javascript"></script>
    <script src="{% static 'js/script.js' %} " type="text/javascript"></script>

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
{#    <link rel="stylesheet" href="{% static 'css/style.css' %}">#}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

</head>
<body>

<div class="col-md-12 mx-auto my-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'bank:bank' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'directors:directors' %}">Директора</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'company:company' %}">Компании</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bank:bank_all' %}">Банки</a>
                </li>

            </ul>
        </div>
    </nav>
    <div class="container-xxl">
        <div class="container text-center">
            <h1> {% block header %} {% endblock header %}</h1>
        </div>
        {% block content %} {% endblock content %}
    </div>
</div>

{% block js %}
    <script>
        $(function () {
            $('[data-tooltip]').tooltip();
        })
        $(function () {
            $('[data-tooltip2]').tooltip();
        })
    </script>
{% endblock js %}
</body>
</html>